apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-v2
  labels:
    app: orders
    version: v2
    color: green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orders
      version: v2
  template:
    metadata:
      labels:
        app: orders
        version: v2
        color: green
    spec:
      containers:
      - name: orders
        image: orders-microservice:v2
        ports:
        - containerPort: 80
        env:
        - name: VERSION
          value: "v2"
